### ISSUE TITLE
Winter credit

### ISSUE THREAD

**Issue by ohmer1** [titilambert/pyhydroquebec#61]
Is there plan to add winter credit support? I would be interested to know when there is peak event.

https://www.hydroquebec.com/residentiel/espace-clients/tarifs/option-credit-hivernal.html

**Comment by dgagnon720** [comment]
same for me, my openhab is ready but I need to activate it manually.  It would be nice to have a status for it.

**Comment by roger1233** [comment]
If I can help (test or otherwise) let me know and I'll be happy to.

**Comment by tech165** [comment]
I created a PR for this, you will see the message you see in your account for today and tomorrow in 2 new MQTT sensors or with command line. You will need to process the message to extract the time in your Home Assistant (or anything else).

**Comment by roger1233** [comment]
I just downloaded the PR, for now my "today_message", today_times and tomorrow_message and tomorrow_times are "unknown" in Home Assistant, I imagine because there is no message for today or tomorrow, but I'll update when I get one, and how I integrate this with HA.

For now, I have a node-red flow that executes at each 6 hours, that check my unread mails and applies a regex on the hydro message to get the times. It works, but I'd like to get rid of that.

**Comment by tech165** [comment]
Hi, yes the "unknown" is because there is nothing yet today. For home assistant I use this automation : 

```yaml
- id: 'xxxxxxxxxxx'
  alias: Tarif Dynamique Hydro-Québec AutoON AM
  description: Lire MQTT et mettre les input_boolean a ON automatique
  trigger:
  - platform: state
    entity_id: sensor.hydroquebec_xxxxxxxxx_today_times
  condition:
  - condition: template
    value_template: "{% if states(\"sensor.hydroquebec_xxxxxxxxx_today_times\") ==\
      \ \"unknown\" %}\n      False\n{% elif states(\"sensor.hydroquebec_xxxxxxxxx_today_times\"\
      ) == \"\" %}\n      False\n{% else %}\n     {% set today_times = states(\"sensor.hydroquebec_xxxxxxxxx_today_times\"\
      )|from_json %}\n     {% if today_times.today_start_1 != \"\" and today_times.today_end_1\
      \ != \"\" %}\n       {% if states(\"sensor.time\") < \"{:02}:{:02}\".format(today_times.today_start_1\
      \ | int, 0) %} \n         True\n       {% else %}\n         False\n       {%\
      \ endif %}\n     {% else %}\n       False\n     {% endif %}\n {% endif %}"
  action:
  - service: input_boolean.turn_on
    data: {}
    entity_id: input_boolean.tarif_dynamique_am
  mode: single
```

I use this 2 of those automation (one for AM and one for PM replacing today_start_1 by today_start_2 ans end_1 by end_2) to turn on an input boolean to on. Then I have other automations based on time and with the condition that this input boolean is turned on to adjust the temperature. 

With the MQTT server in docker and with the config_cron.yaml and entrypoint_cron.sh it will check at 2 am every day so well before the minimum time to turn down the heat.
